# Generated by Django 3.2 on 2024-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_products_has_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='guid',
            field=models.CharField(blank=True, default='', max_length=40, unique=True),
        ),
    ]
