# Generated by Django 3.2 on 2024-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0003_auto_20231114_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='guid',
            field=models.CharField(blank=True, default='', max_length=40, unique=True),
        ),
    ]
